name: App Preview
on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]

jobs:
  update:
    if: '! github.event.pull_request.draft'
    name: Update Expo.dev app preview
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Check for EXPO_TOKEN
        run: |
          if [ -z "${{ secrets.EXPO_TOKEN }}" ]; then
            echo "You must provide an EXPO_TOKEN secret linked to this project's Expo account in this repo's secrets. Learn more: https://docs.expo.dev/eas-update/github-actions"
            exit 1
          fi

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: npm

      - name: Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Install dependencies
        run: npm ci
        
      - name: Create preview
        uses: expo/expo-github-action/preview@v8
        with:
          command: >-
            eas update
            --auto
            --platform ios
  fail:
    if: github.event.pull_request.draft == true
    name: Fail on draft pull request
    runs-on: ubuntu-latest
    steps:
      - name: Fail
        run: |
          echo "This is a draft pull request. Please mark it as ready for review to trigger the app preview."
          echo "Please note API limits for free tier users: https://expo.dev/pricing"
          exit 1
